HomeWork 1
infinum-academy/js-react-academy-2024-iruzevic pull request #1
Opened 2024-07-02 18:35 UTC by iruzevic

### Added
- Local storage helpers
- Initial HTML, CSS files
- JS functionality

### ToDo:

- [ ] On delete event
- [ ] Reorder review
- [ ] Prevent unnecessary rerendering of all items
- [ ] Add little more styling

2024-07-03 10:02 UTC, veksi requested changes
Almost perfect, 99% :D 
Nešto sam i naučio iz ovog, template element 👍  (vidi se da radis WP)
Postoji bug u brisanju elemenata samo.

2024-07-03 10:02 UTC, veksi commented on project/index.js
> +	reviews.forEach((review) => totalRating += review.rating);
Zašto ne zakomplicirati život 😄
```suggestion
	const totalRating = reviews.reduce((acc, review) => {
		return acc + parseInt(review.rating);
	}, 0) / reviews.length;
```

2024-07-03 10:02 UTC, veksi commented on project/index.js
> +			getLocalStorage(storageName).filter((t) => JSON.stringify(t) !== JSON.stringify(review))
Ovo neće raditi u slučaju da imaš iste reviewove (isti rating i content), tj. obrisat će sve iste ratinge a ne samo onaj koji si kliknio

2024-07-03 10:02 UTC, veksi commented on project/styles.css
> +.rating-stars[data-rating='1'] > :nth-child(-n+1),
Trebalo mi je malo da skuzim sta je pjesnik htio reći ali 👍 .

2024-07-03 13:20 UTC, veksi approved these changes
Pls samo rješiš onaj bug sa brisanjem i GG!

2024-07-05 06:42 UTC, iruzevic commented on project/index.js
> +			getLocalStorage(storageName).filter((t) => JSON.stringify(t) !== JSON.stringify(review))
done, tnx

2024-07-05 06:42 UTC, iruzevic commented
All done

2024-07-05 12:52 UTC, veksi approved these changes
❤️

2024-07-05 12:52 UTC, merged