Homework 3
infinum-academy/js-react-academy-2024-iruzevic pull request #3
Opened 2024-07-15 07:36 UTC by iruzevic

### Added
- components for auth
- components for listing and single
- connecting to api

2024-07-16 08:56 UTC, veksi requested changes
Top, samo baci oko na komentare da ovo napravimo TopNaKvadrat :D 
Ako nesto nije jasno vici pa prodjemo skupa!

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/app/(auth)/layout.tsx
> +					bgColor={"purple.600"}
```suggestion
					bgColor="purple.600"
```

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/app/(auth)/layout.tsx
> +		<AuthRedirect>
Mislim da smo pričali o ovome, ovo je good enough ali nema razloga zašto ne staviti `AuthRedirect` na svaki page (na kojem nam treba) zasebno.
Ne moraš "ispravljati" ako ne stigneš, ali čisto da ne mislis da je to losa praksa.

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/app/all-shows/[id]/page.tsx
> +			<LayoutWithSidebar>
Ovo nam je zasad okej, vidjet ces bonus zadatak u novoj zadaći kako rješit ovaj dio bez da wrappas svaki page zasebno.
-> nextjs route groups

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/auth/LoginForm/LoginForm.tsx
> +				<Input {...register("email", )} required type="email" />
Validacije bi bilo super da hendlas kroz lib kao sto smo pricali:
```suggestion
				<Input {...register("email", { required: true } )} type="email" />
```

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/auth/LoginForm/LoginForm.tsx
> +				<Input {...register("password")} required type="password" />
Isto kao i gore :)

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/auth/LoginForm/LoginForm.tsx
> +			<FormControl isRequired={true}>
Ovdje smo rekli trebas sloziti:
```suggestion
			<FormControl isInvalid={Boolean(errors.password)}>
```
errors dolazi is useForm: (komentar gore)

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/auth/LoginForm/LoginForm.tsx
> +	const {register, handleSubmit} = useForm<ILoginFormInputs>();
```suggestion
	const {register, formState: { errors }, handleSubmit} = useForm<ILoginFormInputs>();
```

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/auth/LoginForm/LoginForm.tsx
> +			<FormControl isRequired={true}>
Vidio si na predavanju kako onda mozes prikazati i neki validation message sa `FormErrorMessage` kad imamo ovaj `isInvalid` na `FormControl`.

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/auth/RegisterForm/RegisterForm.tsx
> +			<FormControl isRequired={true}>
Sve isto kao i za `LoginForm`

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/review/ReviewItem/ReviewItem.tsx
> +	useEffect(() => {
Mislim da review imas odmah u trenutku kad zelis renderati ovu komponentu.
U tom slucaju rekao bih da nam ne treba ni useEffect ni state.

mozes sloziti ovo direktno  kao:
`const canDelete = review.user.email === getCurrentUserEmail();` (na liniji 16) i koristiti dalje.

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowListSection/ShowListSection.tsx
> +	const { isLoading } = useSWR(showList, fetcherSecure, {
useSWR vraća i `data`, nema potrebe da na onSuccess data.shows spremas u state, mozes to koristiti direktno:
```suggestion
	const { isLoading, data } = useSWR(showList, fetcherSecure, {
```

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +	} = useSWRMutation(swrKeys.showListItem(showId), fetcherSecure, {
Ovo je okej, ali fetchanje (GET) zelimo raditi sa useSWR hookom, a mutacije (useSWRMutation) cemo ostaviti za sve POST/PATCH/PUT/DELETE akcije.
Ako imas nekih problema sa useSWR pingaj pa prodjemo skupa.
Isto tako nisu nam potrebni state (ni za card ni za listu ovdje)

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +	const {
Isto kao i komentar gore

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +	const { trigger: triggerReviewAdd } = useSWRMutation(swrKeys.reviewsList, mutatorSecure);
Ovo je dobar primjer koristenja useSWRMutation! 👍

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +	}, []);
Ovo nam ne treba jednom kad prebacis one gore na useSWR

2024-07-16 08:56 UTC, veksi commented on tv-shows-app/src/components/shared/AuthRedirect/AuthRedirect.tsx
> +export const AuthRedirect = ({ children }: { children: React.ReactNode }) => {
💪

2024-07-20 18:03 UTC, iruzevic commented
All done

2024-07-23 13:44 UTC, veksi requested changes
Ovo mi izgleda super ali imas 2 stvari samo:
 - delete review-a si preskocio SWR i vjerovatno si se pogubio :D (prodjemo to skupa)
 - manji improvement kod onSuccess (na login i register formama) gdje mozes sam azurirati cache i ubrzati "login" process

2024-07-23 13:44 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +		const reviewDeleteResponse = await mutatorDeleteSecure(swrKeys.showReviewItem(review.id));
Kreirao si gore useSWRMutation za delete, ali ne koristis njegov trigger za brisanje vec direktno mutator.

2024-07-23 13:44 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +			mutate(swrKeys.showListItem(showId));
Ovo cemo odraditi u nekom onSuccess-u od useSWRMutation-a

2024-07-23 13:44 UTC, veksi commented on tv-shows-app/src/components/features/shows/ShowReviewSection/ShowReviewSection.tsx
> +		<>
Vjerujem da ti ovo ne treba jer imas jedan child element

2024-07-23 13:44 UTC, veksi commented on tv-shows-app/src/components/shared/StarRatingInput/StarRatingInput.tsx
> +						as={hasOnChange ? 'button' : 'div'}
Mislim da nam je ovo u konačnici nepotrebno.
Eventualno radi neke semantike, ali okej mi je ili da je uvijek button ili uvijek div (oba imaju onClick)

2024-07-23 13:44 UTC, veksi commented on tv-shows-app/src/components/features/auth/LoginForm/LoginForm.tsx
> +			router.push('/');
E sad je malo čudno da imamo onSuccess i da gledamo postoji li status error. (Znam da API ima problema) ali ovo je sad nesto sto bi izbjegli...
Htio bih da api pukne ili sam throwati error u boljem formatu da to mogu uhvatiti u onError, ali okej nije presudno.
Ono što bi htio ovdje je nakon login-a, azurirati (mutirati) cache i postaviti svog user-a, a tu ce onda AuthRedirect automatski kickinati i redirectati nas na pocetni page (ne moramo rucno raditi izmijenu rute).

2026-06-02 22:28 UTC, closed without merging